name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        
        
      - name: Build Web Assets
        run: npm run build
        
      - name: Setup Android Platform
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Generate Assets (Logo & Splash)
        run: |
          npm install @capacitor/assets --legacy-peer-deps
          npx @capacitor/assets generate --android
          
      - name: Inject Firebase Config
        run: |
          mkdir -p android/app
          cp google-services.json android/app/google-services.json

      - name: Inject Google Auth ID for Android
        run: |
          mkdir -p android/app/src/main/res/values
          echo '<?xml version="1.0" encoding="utf-8"?><resources><string name="server_client_id">787837715214-bh93hp1tsncrd55m1784ta0bub9d8oti.apps.googleusercontent.com</string></resources>' > android/app/src/main/res/values/google_auth.xml

          
      - name: Inject Location Permissions
        run: |
          sed -i 's/<application/<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" \/>\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" \/>\n    <application/g' android/app/src/main/AndroidManifest.xml
          
      - name: Inject Hardware Permissions
        run: |
          sed -i 's/<application/<uses-permission android:name="android.permission.CAMERA" \/>\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" \/>\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" \/>\n    <application/g' android/app/src/main/AndroidManifest.xml

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build Final APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/certificates/orgo.jks \
            -Pandroid.injected.signing.store.password=123 \
            -Pandroid.injected.signing.key.alias=orgo-key \
            -Pandroid.injected.signing.key.password=123
          
          ./gradlew signingReport \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/certificates/orgo.jks \
            -Pandroid.injected.signing.store.password=123 \
            -Pandroid.injected.signing.key.alias=orgo-key \
            -Pandroid.injected.signing.key.password=123
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OrGo-Mobile-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
